### ISSUE TITLE
Improve container health checks

### ISSUE THREAD

**Issue by michaelstingl** [opencloud-community/opentalk-docker#6]
## Description

The official repository includes more detailed health checks for containers. We should integrate these health checks into our Docker Compose configuration to improve reliability.

## Example Health Checks from Official Repository
```yaml
# Keycloak health check
healthcheck:
  test: curl -fsS http://keycloak:8080/auth/health/ready -o - | grep UP
  interval: 20s
  timeout: 120s
  retries: 10

# PostgreSQL health check
healthcheck:
  test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-opentalk}"]
  interval: 10s
  timeout: 5s
  retries: 5

# RabbitMQ health check
healthcheck:
  test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
  interval: 30s
  timeout: 60s
  retries: 5

# MinIO health check
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  interval: 30s
  timeout: 20s
  retries: 3
```

## Tasks
- [ ] Add health checks to all services in docker-compose.yml
- [ ] Test health checks to ensure they work correctly
- [ ] Document health check configurations
- [ ] Add a monitoring section to the documentation

## References
- Official Repository: https://gitlab.opencode.de/opentalk/ot-setup
- Docker Compose file: https://gitlab.opencode.de/opentalk/ot-setup/-/blob/main/docker-compose.yaml

## Benefits
- Improved reliability of the deployment
- Better monitoring capabilities
- Automatic recovery from service failures
- Better alignment with official repository
